### ISSUE TITLE
On Chrome 56, the page load progress transition causes elements with position:sticky to be invisible

### ISSUE THREAD

**Issue by awikkerink** [BrightspaceUI/page-load-progress#12]
I think it's an issue in Chrome. This is just here to track things

With progress bar:
![kl85-awikkerin-44444-d2l-lms-grades-admin-enter-user_list_view d2l-ou 6609 1](https://cloud.githubusercontent.com/assets/7862298/21811357/6ca864e0-d71d-11e6-920c-b05c06bd71b8.png)

Without progress bar (ignore the positioning issue for the button. ~~It's an unrelated issue~~ --edit see mention):
![kl85-awikkerin-44444-d2l-lms-grades-admin-enter-user_list_view d2l-ou 6609 2](https://cloud.githubusercontent.com/assets/7862298/21811362/6f41b652-d71d-11e6-8769-245b97af3313.png)

**Comment by dbatiste** [comment]
I think page loading progress component is being removed as part of SS rendering nav.  This makes me worry about other transforms though.

**Comment by dlockhart** [comment]
Confirmed that the page-load-progress component will be going away in the next couple weeks with server-side rendered nav.
